### ISSUE TITLE
Passing content non markdown text

### ISSUE THREAD

**Issue by matthewdolman** [deltatre-webplu/proNg-mirror#1]
Whenever I pass invalid markdown to prosemirror I get the following error:

	Token type `html_inline` not supported by Markdown parser

This is a pain because the markdown processor that I use accepts html and shortcodes.

Is there any way to set prosemirror to treat  any text it does not understand as plan text?

**Comment by davideicardi** [comment]
I suspect that this error is generated directly by prose mirror component. So you must probably open an issue on that repository. In you case I suspect that the best solution is to validate markdown before passing it to prose mirror.
